# Generated by Django 5.2.17 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explications_conducteur', models.TextField(blank=True)),
                ('pieces_supplementaires', models.FileField(blank=True, null=True, upload_to='auditions/')),
                ('date_audition', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audition',
                'verbose_name_plural': 'Auditions',
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('REPORTEE', 'Reportée')], default='ENVOYEE', max_length=15)),
                ('lettre_pdf', models.FileField(blank=True, null=True, upload_to='convocations/')),
                ('envoye_sms', models.BooleanField(default=False)),
                ('envoye_email', models.BooleanField(default=False)),
                ('envoye_courrier', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
            },
        ),
        migrations.CreateModel(
            name='SessionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField(default=10, help_text='Nombre de dossiers max pour cette session')),
            ],
            options={
                'verbose_name': 'Session de commission',
                'verbose_name_plural': 'Sessions de commission',
                'ordering': ['-date_session'],
            },
        ),
    ]
