# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convocation',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convocation', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='audition',
            name='convocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audition', to='commissions.convocation'),
        ),
        migrations.AddField(
            model_name='sessioncommission',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='sessions_membre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncommission',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_presidees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convocation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='commissions.sessioncommission'),
        ),
    ]
