# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
import dossiers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('plaque', models.CharField(max_length=30)),
                ('type_vehicule', models.CharField(choices=[('VOITURE', 'Voiture'), ('CAMION', 'Camion'), ('MOTO', 'Moto'), ('AUTRE', 'Autre')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_incident', models.DateTimeField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type_incident', models.CharField(choices=[('CORPOREL', 'Accident corporel'), ('MATERIEL', 'Accident matériel'), ('DELIT_FUITE', 'Délit de fuite'), ('AUTRE', 'Autre infraction grave')], max_length=20)),
                ('vitesse_excessive', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('stupefiants', models.BooleanField(default=False)),
                ('feu_rouge', models.BooleanField(default=False)),
                ('autres_circonstances', models.TextField(blank=True)),
                ('nombre_blesses', models.PositiveIntegerField(default=0)),
                ('nombre_deces', models.PositiveIntegerField(default=0)),
                ('gravite', models.CharField(blank=True, max_length=50)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modif', models.DateTimeField(auto_now=True)),
                ('modification_validee_hierarchie', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('SAISI', 'Saisi (en attente de vérification)'), ('COMPLEMENT_DEMANDE', 'Complément demandé'), ('VERIFIE', 'Vérifié / transmis à la commission'), ('REJETE', 'Rejeté'), ('PROGRAMME', 'Programmé en commission'), ('DECIDE', 'Décision rendue'), ('CLOTURE', 'Clôturé / archivé')], default='SAISI', max_length=25)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('agent_saisisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_saisis', to=settings.AUTH_USER_MODEL)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='dossiers.conducteur')),
                ('verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_verifies', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='dossiers.vehicule')),
            ],
            options={
                'verbose_name': 'Dossier de confiscation',
                'verbose_name_plural': 'Dossiers de confiscation',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='dossiers.dossier')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique du dossier',
                'verbose_name_plural': 'Historiques des dossiers',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('PERMIS', 'Photo du permis confisqué'), ('CARTE_GRISE', 'Photo de la carte grise'), ('PV_ACCIDENT', "PV d'accident"), ('CONSTAT_MEDICAL', 'Constatations médicales'), ('AUTRE', 'Autre pièce')], max_length=20)),
                ('fichier', models.FileField(upload_to=dossiers.models.chemin_upload_piece)),
                ('uploade_le', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
