# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_decision', models.CharField(choices=[('RELAXE', 'Relaxe (restitution immédiate)'), ('SUSPENSION', 'Suspension temporaire'), ('RETRAIT_DEFINITIF', 'Retrait définitif'), ('FORMATION_OBLIGATOIRE', 'Obligation de formation')], max_length=25)),
                ('duree_suspension_mois', models.PositiveIntegerField(blank=True, help_text='Durée en mois (1 à 36) si suspension temporaire', null=True)),
                ('motivation', models.TextField(help_text='La décision doit être motivée (obligatoire)')),
                ('arrete_pdf', models.FileField(blank=True, null=True, upload_to='decisions/')),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('notifie_sms', models.BooleanField(default=False)),
                ('notifie_email', models.BooleanField(default=False)),
                ('notifie_courrier', models.BooleanField(default=False)),
                ('transmis_tribunal', models.BooleanField(default=False, help_text='Si retrait définitif')),
                ('audition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='commissions.audition')),
                ('decide_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Décision',
                'verbose_name_plural': 'Décisions',
            },
        ),
    ]
