# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_restitution_pdf', models.FileField(blank=True, null=True, upload_to='restitutions/')),
                ('date_remise', models.DateTimeField(blank=True, null=True)),
                ('piece_identite_verifiee', models.BooleanField(default=False)),
                ('rappel_envoye', models.BooleanField(default=False, help_text="Rappel automatique 7 jours avant l'échéance de suspension")),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restitution', to='decisions.decision')),
                ('remis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restitution',
                'verbose_name_plural': 'Restitutions',
            },
        ),
    ]
